modified:   .github/workflows/dspace-virtual-workbench-ci-demo.yaml 	modified:   .github/workflows/one-time-simulation-and-test-with-ta-sdk-using-aws-windows-runner.yaml

diff --git a/.github/workflows/dspace-virtual-workbench-ci-demo.yaml b/.github/workflows/dspace-virtual-workbench-ci-demo.yaml
--- a/.github/workflows/dspace-virtual-workbench-ci-demo.yaml
+++ b/.github/workflows/dspace-virtual-workbench-ci-demo.yaml
@@ -3,6 +3,14 @@ name: dSPACE Virtual Workbench CI Demo
 on:
   workflow_dispatch:
 
+env:
+  JOB_1_PYTHON_SDK_DIR: PythonSDK_Turnlamp
+  JOB_1_OPENTA_TESTENV_CONFIG: testdata/testenv_veos_linux.yaml
+  JOB_2_PYTHON_SDK_DIR: PythonSDK_ScbT
+  JOB_2_OPENTA_TESTENV_CONFIG: tests/testdata_scbt/testenv_asm_veos_linux.yaml
+  JOB_3_PYTHON_SDK_DIR: PythonSDK_Turnlamp
+  JOB_3_OPENTA_TESTENV_CONFIG: testdata/testenv_veos.yaml
+
 permissions:
   contents: write
   actions: write
@@ -47,7 +55,7 @@ jobs:
 
 
   job-1-start-runner:
-    name: Job 1 - Start One-Time EC2 Windows Runner
+    name: Job 1 - Start One-Time EC2 Linux Runner
     needs:
       - build-controller-model
       - build-plant-model
@@ -59,9 +67,9 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 1
-      - name: Start One-Time EC2 Windows Runner
+      - name: Start One-Time EC2 Linux Runner
         id: start-ec2-runner
-        uses: ./.github/actions/start-one-time-windows-ec2-runner
+        uses: ./.github/actions/start-one-time-linux-ec2-runner
         with:
           runner-labels: job-1-dspace-simulation-and-test-${{ github.run_id }}
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
@@ -73,7 +81,7 @@ jobs:
           security-group-id: ${{ vars.AWS_SECURITY_GROUP_IDS }}
           iam-instance-profile: ${{ vars.AWS_IAM_INSTANCE_PROFILE_NAME }}
           key-name: ${{ vars.AWS_SSH_KEY_PAIR_NAME }}
-          ami-id: ami-0dc0f13e8dbac09d4   # Windows TA_SDK AMI
+          ami-id: ami-0bb50ff1709190a42   # Linux TA_SDK AMI
           instance-type: t3.2xlarge
           ebs-volume-size: 500
           
@@ -104,34 +112,33 @@ jobs:
             echo
             echo "| Parameter | Value |"
             echo "|-----------|-------|"
-            echo "| 📂 Python uv directory | \`PythonSDK/Turnlamp\` |"
-            echo "| 📝 Python test script path | \`tests/test_turnlamp.py\` |"
-            echo "| ⚙️ OpenTA test environment config | \`tests/testdata_turnlamp/testenv_veos.yaml\` |"
+            echo "| 📂 Python SDK Directory | \`${{ env.JOB_1_PYTHON_SDK_DIR }}\` |"
+            echo "| ⚙️ OpenTA TestEnv Config File | \`${{ env.JOB_1_OPENTA_TESTENV_CONFIG }}\` |"
           } >> $GITHUB_STEP_SUMMARY
                     
       - name: Run pytest with Allure reporting
-        shell: powershell
+        shell: bash
         run: |
-          Write-Host "Hello dSPACE World!"
+          echo "Hello dSPACE World!"
 
           # Add dSPACE license server to CodeMeter Server Search List
-          Write-Host "Adding dSPACE license server to CodeMeter Server Search List ..."
-          Start-Process -FilePath "C:\Program Files (x86)\CodeMeter\Runtime\bin\cmu32.exe" -ArgumentList "--add-server ${{ vars.AWS_DSPACE_LICENSE_SERVER }}" -Wait -NoNewWindow
+          echo "Adding dSPACE license server to CodeMeter Server Search List ..."
+          cmu --add-server ${{ vars.AWS_DSPACE_LICENSE_SERVER }}
 
           # Install uv
-          powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
-          $env:Path = "C:\Users\Administrator\.local\bin;$env:Path"
+          curl -LsSf https://astral.sh/uv/install.sh | sh
+          source $HOME/.local/bin/env 
           
-          # Start VEOS
-          & 'C:\Program Files\dSPACE XIL API .NET 2024-A\PlatformManagementAPI\Main\bin\CmdLoader.exe' -rnc 127.0.0.1 -t VEOS -af 0 -start
-          
-          # Run pytest with Allure Results
-          cd PythonSDK/Turnlamp
-          uv sync
-          uv run pytest tests/test_turnlamp.py --openta-testenv-config=tests/testdata_turnlamp/testenv_veos.yaml --alluredir=allure-results
+          # Register & Start VEOS
+          echo "Registering & Starting VEOS ..."
+          /opt/dspace/xilapi2024a/MAPort/Main/bin/CmdLoader -rnc 127.0.0.1 -t VEOS -af 0 -start || true          
 
-          # exit 1    # means failure result
-          # exit 0    # means success result
+          # Run pytest with Allure Results
+          cd "${{ env.JOB_1_PYTHON_SDK_DIR }}"
+          uv sync
+          uv run pytest ./tests --openta-testenv-config="${{ env.JOB_1_OPENTA_TESTENV_CONFIG }}" --alluredir=./allure-results
+          # exit 1  # failed
+          # exit 0  # success
 
       - name: Upload Allure Results
         uses: actions/upload-artifact@v4
@@ -139,7 +146,7 @@ jobs:
         continue-on-error: true
         with:
           name: job-1-allure-results
-          path: PythonSDK/Turnlamp/allure-results
+          path: ${{ env.JOB_1_PYTHON_SDK_DIR }}/allure-results
           retention-days: 30
           if-no-files-found: warn
 
@@ -168,7 +175,7 @@ jobs:
 
 
   job-2-start-runner:
-    name: Job 2 - Start One-Time EC2 Windows Runner
+    name: Job 2 - Start One-Time EC2 Linux Runner
     needs:
       - build-controller-model
       - build-plant-model
@@ -180,9 +187,9 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 1
-      - name: Start One-Time EC2 Windows Runner
+      - name: Start One-Time EC2 Linux Runner
         id: start-ec2-runner
-        uses: ./.github/actions/start-one-time-windows-ec2-runner
+        uses: ./.github/actions/start-one-time-linux-ec2-runner
         with:
           runner-labels: job-2-dspace-simulation-and-test-${{ github.run_id }}
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
@@ -194,7 +201,7 @@ jobs:
           security-group-id: ${{ vars.AWS_SECURITY_GROUP_IDS }}
           iam-instance-profile: ${{ vars.AWS_IAM_INSTANCE_PROFILE_NAME }}
           key-name: ${{ vars.AWS_SSH_KEY_PAIR_NAME }}
-          ami-id: ami-0dc0f13e8dbac09d4   # Windows TA_SDK AMI
+          ami-id: ami-0bb50ff1709190a42   # Linux TA_SDK AMI
           instance-type: t3.2xlarge
           ebs-volume-size: 500
           
@@ -225,34 +232,33 @@ jobs:
             echo
             echo "| Parameter | Value |"
             echo "|-----------|-------|"
-            echo "| 📂 Python uv directory | \`PythonSDK/ScbT\` |"
-            echo "| 📝 Python test script path | \`tests/test_scbt.py\` |"
-            echo "| ⚙️ OpenTA test environment config | \`tests/testdata_scbt/testenv_asm_veos.yaml\` |"
+            echo "| 📂 Python SDK Directory | \`${{ env.JOB_2_PYTHON_SDK_DIR }}\` |"
+            echo "| ⚙️ OpenTA TestEnv Config File | \`${{ env.JOB_2_OPENTA_TESTENV_CONFIG }}\` |"
           } >> $GITHUB_STEP_SUMMARY
                     
       - name: Run pytest with Allure reporting
-        shell: powershell
+        shell: bash
         run: |
-          Write-Host "Hello dSPACE World!"
-          
+          echo "Hello dSPACE World!"
+
           # Add dSPACE license server to CodeMeter Server Search List
-          Write-Host "Adding dSPACE license server to CodeMeter Server Search List ..."
-          Start-Process -FilePath "C:\Program Files (x86)\CodeMeter\Runtime\bin\cmu32.exe" -ArgumentList "--add-server ${{ vars.AWS_DSPACE_LICENSE_SERVER }}" -Wait -NoNewWindow
+          echo "Adding dSPACE license server to CodeMeter Server Search List ..."
+          cmu --add-server ${{ vars.AWS_DSPACE_LICENSE_SERVER }}
 
           # Install uv
-          powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
-          $env:Path = "C:\Users\Administrator\.local\bin;$env:Path"
+          curl -LsSf https://astral.sh/uv/install.sh | sh
+          source $HOME/.local/bin/env 
           
-          # Start VEOS
-          & 'C:\Program Files\dSPACE XIL API .NET 2024-A\PlatformManagementAPI\Main\bin\CmdLoader.exe' -rnc 127.0.0.1 -t VEOS -af 0 -start
-          
-          # Run pytest with Allure Results
-          cd PythonSDK/ScbT
-          uv sync
-          uv run pytest tests/test_scbt.py --openta-testenv-config=tests/testdata_scbt/testenv_asm_veos.yaml --alluredir=allure-results
+          # Register & Start VEOS
+          echo "Registering & Starting VEOS ..."
+          /opt/dspace/xilapi2024a/MAPort/Main/bin/CmdLoader -rnc 127.0.0.1 -t VEOS -af 0 -start || true          
 
-          # exit 1    # means failure result
-          # exit 0    # means success result
+          # Run pytest with Allure Results
+          cd "${{ env.JOB_2_PYTHON_SDK_DIR }}"
+          uv sync
+          uv run pytest ./tests --openta-testenv-config="${{ env.JOB_2_OPENTA_TESTENV_CONFIG }}" --alluredir=./allure-results
+          # exit 1  # failed
+          # exit 0  # success
 
       - name: Upload Allure Results
         uses: actions/upload-artifact@v4
@@ -260,7 +266,7 @@ jobs:
         continue-on-error: true
         with:
           name: job-2-allure-results
-          path: PythonSDK/ScbT/allure-results
+          path: ${{ env.JOB_2_PYTHON_SDK_DIR }}/allure-results
           retention-days: 30
           if-no-files-found: warn
 
@@ -345,10 +351,9 @@ jobs:
             echo "### 🧪 Test Information"
             echo
             echo "| Parameter | Value |"
-            echo "|-----------|--------|"
-            echo "| 📂 Python uv directory | \`PythonSDK/Turnlamp\` |"
-            echo "| 📝 Python test script path | \`tests/test_turnlamp_all_pass.py\` |"
-            echo "| ⚙️ OpenTA test environment config | \`tests/testdata_turnlamp/testenv_veos.yaml\` |"
+            echo "|-----------|-------|"
+            echo "| 📂 Python SDK Directory | \`${{ env.JOB_3_PYTHON_SDK_DIR }}\` |"
+            echo "| ⚙️ OpenTA TestEnv Config File | \`${{ env.JOB_3_OPENTA_TESTENV_CONFIG }}\` |"
           } >> $GITHUB_STEP_SUMMARY
                     
       - name: Run pytest with Allure reporting
@@ -368,12 +373,11 @@ jobs:
           & 'C:\Program Files\dSPACE XIL API .NET 2024-A\PlatformManagementAPI\Main\bin\CmdLoader.exe' -rnc 127.0.0.1 -t VEOS -af 0 -start
           
           # Run pytest with Allure Results
-          cd PythonSDK/Turnlamp
+          cd "${{ env.JOB_3_PYTHON_SDK_DIR }}"
           uv sync
-          uv run pytest tests/test_turnlamp_all_pass.py --openta-testenv-config=tests/testdata_turnlamp/testenv_veos.yaml --alluredir=allure-results
-
-          # exit 1    # means failure result
-          # exit 0    # means success result
+          uv run pytest ./tests --openta-testenv-config="${{ env.JOB_3_OPENTA_TESTENV_CONFIG }}" --alluredir=./allure-results
+          # exit 1  # failed
+          # exit 0  # success
 
       - name: Upload Allure Results
         uses: actions/upload-artifact@v4
@@ -381,7 +385,7 @@ jobs:
         continue-on-error: true
         with:
           name: job-3-allure-results
-          path: PythonSDK/Turnlamp/allure-results
+          path: ${{ env.JOB_3_PYTHON_SDK_DIR }}/allure-results
           retention-days: 30
           if-no-files-found: warn
 
